### ISSUE TITLE
Start?

### ISSUE THREAD

**Issue by Tagguritt** [moeseven/DungeonGame2#2]
I can't seem to find where the program is meant to start. **:'(** The idea sounds super cool, but i can't tell where it is meant to start.

**Comment by moeseven** [comment]
Thank you for your comment. This is still in the very beginning of development. 
So far there are only some basic classes. There is a main in the gui package where you can play one fight vs two goblins but its very basic.

**Comment by Tagguritt** [comment]
NP. I am still trying to figure git-hub out.
